const commandRegex = /(quote|ooc|lambda-quotes)/;
function processCommand(command) {
  const quotes = [
    "\"I need Pikachu to say fuck!\" - Robert K.",
    "\"I heard \'first-grade Nathan\', now I\'m interested\" - Jeff H.",
    "\"Were you there when I said that really inappropriate thing about cream cheese?\" - Justin",
    "\"I\'ll be right back.\" *distant yelling* - Nathan P.",
    "\"Come novel my marvelties.\" - Chris G.",
    "\"I\'m worried if I stare at him too long I\'ll become straight.\" - Aditya D.",
    "\"Chris, get over here! We\'re gonna cop on Michael!\" - Michael G.",
    "\"It\'s the economics of giving birth!\" - Cory R.",
    "\"I am *gord*an Rams*ey\'s Skeleton\" - Foster H.\n*Note: Did you mean \"Gordon Ramsay\"?\nThis document was last edited by Foster",
    "\"In front of us is the rural king, twis the source of my salt\" - Aden K.",
    "\"It would work if they were bigger\" - Dustin G.",
    "\"I spent ***72*** days pushing you out of my vagina!\" - Foster the hairy ghost (Foster H.)",
    "\"Cory, Just fucking shove it in your fuck.\" - Micky G (Michael G.)",
    "\"My campaign starts with giving Steven head!\" - Antonio J.",
    "\"I\'m more secure about my tiny penis\" - Shane S.",
    "\"given my financial situation, I\'d do it for 20$\" - christian, cheer (Chris S.)",
    "\"If I die, I want to die in high res.\" - Foster H.",
    "\"Damn, slaves are expensive.\" - Lowrey (Thomas L.)",
    "\"If I can\'t go with the Amish, I\'m going to sell my self into slavery\" - A. Niccum",
    "\"I will suck your dick [...] this is life or death!\" - A. Niccum",
    "\"I\'m more than willing to be your slave and lick your balls.\" - A. Niccum",
    "\"They can have a thicc ass princess and I\'d be on board for that.\" - Gerg (Greg K.)",
    "\"Greg, this is God.\" - God",
    "\"Every businessman has a wife to fuck in the ass, even the women.\" - A. Niccum",
    "\"Greg has a 6 foot thick dick\" - Emily",
    "\"Everyone's assaulting me with liquids tonight\" - Gerg (Greg K.)",
    "\"Do you have to seduce a cupacabra?\" - Lee (Duane K.)",
    "\"Is the Kama Sutra open source?\" - niggum (Austin N.)",
    "\"The Purge is always happening in Mexico\" - Niggum (Austin N.)",
    "\"Wait, how do you spell Anal?!\" - Niggum (Austin N.)",
    "\"Only a white gay man can handle this black ass\" - A. Niccum",
    "\"I would love to be that man\'s garbage can...\" - Jeff P., called out by Dustin",
    "\"Y\'all can judge me for this if you want, but I\'m saving these.\" - Dan H.",
    "\"I love getting shat on.\" - Lowrey (Thomas L.)",
    "\"The real hole was the friends we made along the way\" - Niggum (Austin N.)",
    "\"We are LEEEEgion\" - Chris H.",
    "\"Only killing\nOnly killing Shrek can sustain me!\" - A. Niccum",
    "\"It\'s those Indians and their damn Halloween\" - Dan H.",
    "\"Play stupid games, win stupid prizes\" - Chris H.",
    "\"There is no way that is not coming out of an ass\" - Jenner W.",
    "\"Gunnar, are you a MILF?\" - Niccum\n\"Yes...\" - Gunnar H.",
    "\"You can only say no if Gunnar uses his MILF dick\" - A. Niccum",
    "\"I\'m a god, suck my dick.... I DIDN\'T MEAN IT\" - Gerg (Greg K.)",
    "\"They have to be very attractive for me to forget they have a penis\" - Dan H.",
    "\"I have an issue that the balls aren\'t there.\" - Dan H.",
    "\"Do a lot. That\'s big and it hurts.\" - Dustin",
    "\"I\'m the hermaphrodite\" - Dustin",
    "\"Maybe I should just move up to Michigan and Dustin can be your wife\" - Emily",
    "\"Only breasts can sustain me\" - A. Niccum",
    "\"I think I can kill a 3-year-old\" - A. Niccum",
    "\"Let me show you a picture of my fermentation bucket\" - Greg K.",
    "\"Here\'s the problem with a pet pig, I\'d get way too attached and when it dies, I\'d eat it and feel bad\" - Greg K.",
    "\"I don\'t want to be a priest, but...\" - Chris H.",
    "\"We can kill this teenage girl if we need to\" - Niggum (Austin N.)",
    "\"The real gender was the friends we made along the way\" - Niggum (Austin N.)",
    "\"Oh my god, it does taste like cum!\" - Graham H.",
    "\"God damnit! Why are you having sex with him? He has the plauge!\" - the Swag God",
    "\"Prostitutes are honest\" - Niggum (Austin N.)",
    "\"Good thing most of the whites were eliminated\" - Nathan",
    "\"I want you to make that noise again, I need to take my pants off first.\" - Gerg (Greg K.)",
    "\"I enjoy the gagging\" - Gerg (Greg K.)",
    "\"I fap with my tounge\" - Greg K.",
    "\"I\'m addicted to, like, three drugs now. Let\'s do this!\" - Gerg (Greg K.)",
    "\"I was going to be like spiderman, but with Jizz.\" - Gerg (Greg K.)",
    "\"I have great experience locking up women\" - Greg K.",
    "\"Is it still a MILF if they fathered the child?\" - Dustin G.",
    "\"There\'s being fat, and then tehre is meat salad with tater tots.\" - Gerg (Greg K.)",
    "\"You will never be able to ship your prostitutes through my cockade\" - Gerg (Greg K.)",
    "\"Get you hands off my combover\" - A. Niccum",
    "\"Oh God! That sausage almost hit me\" - J-Wile (Jenner W.)",
    "\"You know you could learn how to cook\"\n\"PFFFT! I have a WIFE Greg!\" - Jenner W.",
    "\"I\'ve been to japan, they don\'t have beards unless they\'re 80, and Chinese\" - Niggum (Austin N.)",
    "\"I\'d like to introduce the Jim Crow Laws...\" -LLL",
    "\"I have achieved sexual nirvana.\" - Gerg (Greg K.)",
    "\"I feel like Lee and me connect on a sexual level\" - Greg K.",
    "\"I call dibs on the penis\" - Krizz (Chris H.)",
    "\"I cast detect THOTs\" - The Swag",
    "\"I don\'t nkow who I hate more, the people who use the terms millenials and snowflakes, or the people they\'re referring to...\" - A. Niccum",
    "\"I wouldn\'t be surprised if Gunnar were Chinese\" - Greg K.",
    "\"I just want a Grimace butt plug with a purple fur coat\" - Kelsi",
    "\"I am the masturbatorium!\" - Niggum (Austin N.)",
    "\"Nothing like a cold refreshing cat at the end of the day\" - Gerg (Greg K.)",
    "\"Where\'s that nice young man who said he wanted to fuck my pussy?\" - Niggum (Austin N.)",
    "\"What if he paid her in dick?\" - A. Niccum",
    "\"Lowrey, your dick is a deity in my world.\" - The Eternal Gerg (Greg K.)",
    "\"His entire body was a sentient dildo. If that doesn\'t seduce the woman, what will?\" - Dustin G.",
    "\"We can just load her into a trebuchet...\" - Lee (Duane K.)",
    "\"Jokes on you, I\'ll just keep a knife in my asshole!\" - Shane S.",
    "\"She\'s touching my sword and there\'s very little consent\" - Ryan E.",
    "\"Sure Michael... Just find a father that would let you fuck his 12 year old daughter\" - Justin E.",
    "\"ALL casualties here are justified! I\'ll commit genocide if I have to, I don\'t fucking care!\" - Shane S.",
    "\"My mouth can take a lot of abuse\" - Chris S.",
    "\"Oh no, you lost your white power!\" - Chris S.",
    "\"Yes, my dick is in my mouth.\" - Tyler R.",
    "\"Jay, Just let me nut in you\" - Shane S.",
    "\"I don\'t know about you but I don\t want my girl to crash midway through a blowjob\" - Steven D.",
    "\"It doesn\'t mean I can\'t be black if I want to\" - Ben S.",
    "\"I\'m the black king\" - Riley M.",
    "\"Shut up, Chris, I have the weed in my head!\" - Ryan E.",
    "\"Stop f****ing writing down stupid quotes\" - Cory R.",
    "\"Foster, you sure know how to climb on someone without making it arousing.\" - Chris S.",
    "\"Did I give them all to chari... I fucking hate charity\" - Chris S.",
    "\"I\'ll let you lick it when I\'m done.\" - Shane S.",
    "\"I\'ll suck your dick if you make me a burger\" - J Myers",
    "\"I feel like a football player, just tuck the gay under my arm and run to the endzone.\" - Cory R.",
    "\"Aw, now I wish I had Autism, so I\'d be good at Physics.\" - Zane B.",
    "\"I\'m not going to admit I got spooked by an incest anime.\" - Shane S.",
    "\"I punched a kid for the right reason\" - Shane S.",
    "\"You\'ve made your cum-stain now sit in it.\" - Chris S. / Aditya D.",
    "\"It is 4:52 in the morning and I am THIS close to bitch-slapping my grandpa\" - Aditya D.",
    "\"Gay people are horrible\" - Aditya D.",
    "\"Please, FOR THE LOVE OF GOD, do NOT re-awaken sexually curious Shane from middle school.\" - Shane S.",
    "\"I really like deep holes.\" - Riley M.",
    "\"if you integrate a love ODE do you have a load\" - Dan (Timothy P.)",
    "\"I heard something I did not understand and my mind immediately jumped to genocide and non-conventional warfare.\" - Chris S.",
    "\"He just swoops in, takes a massive shit in Cory\'s cornflakes, then leaves\" - Shane S.",
    "\"That\'s not even homosexual, that\'s just... gay.\" - Aditya D.",
    "\"Jenner\'s never been wrong, ...Don\'t quote me on that\" - Antonio J.",
    "\"Can turtles jackhammer their dicks? Like - waaa\" - J Myers",
    "\"I want to be paid if you\'re making porn of me.\" - Chris S.",
    "\"I\'ll take a half-chub for a puppet-show.\" - Chris S."
  ];
  return quotes[Math.floor(Math.random() * quotes.length)];
}

module.exports = {
	commandRegex,
	processCommand
};
